/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's knowledge bases */
        get: operations["list"];
        put?: never;
        /** Create a knowledge base */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/runs/{runId}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert a run, synchronously */
        post: operations["revert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/quiz-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a quiz over a study scope */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/quiz-sessions/{sessionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer the current question and get it graded */
        post: operations["answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/query-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's past questions and answers, newest first */
        get: operations["history"];
        put?: never;
        /** Start a Query conversation */
        post: operations["start_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/query-sessions/{interactionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question, answered from the wiki with page citations */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/query-sessions/{interactionId}/edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the wiki from chat; the edit runs as a queued ingest run */
        post: operations["edit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/lint-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a full review */
        post: operations["startLint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/flashcards/{cardId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate a card and reschedule it */
        post: operations["review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploaded documents with their latest run */
        get: operations["list_1"];
        put?: never;
        /** Upload a document; its ingest run starts after the response */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/documents/{documentId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a document whose latest run failed */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an account and sign in */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out by clearing the session cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the signed-in user's display name */
        patch: operations["update"];
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a knowledge base with its document and page counts */
        get: operations["get"];
        put?: never;
        post?: never;
        /** Delete a knowledge base and everything in it */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Rename or re-describe a knowledge base */
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the knowledge base's runs, newest first */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run's report */
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/quiz-sessions/{sessionId}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the next question's text */
        get: operations["next"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream progress of every run of the knowledge base over SSE */
        get: operations["progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/pages/{directory}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a page rendered with its supersession notes and citations */
        get: operations["page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/pages/{directory}/{name}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a page's revisions, oldest first, so each follows its prior revision */
        get: operations["revisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/pages/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search pages by title, description and body */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the rendered index and its entries */
        get: operations["index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the live health checks and the latest full review */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the live pages and the links between them */
        get: operations["graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/flashcards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open a deck: refresh the scope's cards within the session budget and list the due ones */
        get: operations["deck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the knowledge base as an OKF bundle */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a document with its latest run */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-bases/{kbId}/supersessions/{supersessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one supersession, synchronously */
        delete: operations["removeSupersession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KnowledgeBaseRequest: {
            name: string;
            description?: string;
        };
        KnowledgeBaseResponse: {
            /** Format: uuid */
            kbId: string;
            /** Format: uuid */
            ownerId: string;
            name: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            pageCount: number;
            /** Format: int64 */
            documentCount: number;
        };
        RunAcceptedResponse: {
            /** Format: uuid */
            runId: string;
        };
        QuizSessionRequest: {
            lessonId?: string;
            /** Format: uuid */
            pageId?: string;
        };
        QuizSessionResponse: {
            /** Format: uuid */
            sessionId: string;
            /** Format: int32 */
            questionCount: number;
            /** Format: date-time */
            expiresAt: string;
        };
        AnswerRequest: {
            answer: string;
        };
        EvaluationResponse: {
            /** Format: int32 */
            score: number;
            feedback: string;
            finished: boolean;
        };
        QuerySessionResponse: {
            /** Format: uuid */
            interactionId: string;
        };
        QuestionRequest: {
            question: string;
        };
        AnswerResponse: {
            answer: string;
            citedPaths: string[];
        };
        EditRequest: {
            instruction: string;
            quotedAnswer?: string;
        };
        ReviewRequest: {
            /** Format: int32 */
            rating?: number;
        };
        FlashcardResponse: {
            cardId: string;
            /** Format: uuid */
            pageId: string;
            sectionAnchor: string;
            /** @enum {string} */
            cardType: "BASIC" | "CLOZE" | "REVERSE";
            front: string;
            back: string;
            /** Format: date-time */
            dueAt: string;
        };
        DocumentAcceptedResponse: {
            /** Format: uuid */
            documentId: string;
        };
        RegisterRequest: {
            displayName: string;
            /** Format: email */
            email: string;
            password: string;
        };
        UserResponse: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            email: string;
            avatarUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastLoginAt: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ProfileRequest: {
            displayName: string;
        };
        RunSummaryResponse: {
            /** Format: uuid */
            runId: string;
            /** @enum {string} */
            kind: "INGEST" | "REVERT" | "LINT";
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "WRITTEN" | "COMPLETED" | "FAILED";
            /** Format: uuid */
            documentId: string;
            conversation: boolean;
            lessonTitle: string;
            /** Format: int32 */
            attempt: number;
            retryable: boolean;
            failureReason: string;
            /** Format: int32 */
            created: number;
            /** Format: int32 */
            revised: number;
            /** Format: int32 */
            deleted: number;
            /** Format: int32 */
            supersessionCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt: string;
        };
        FailureResponse: {
            step: string;
            item: string;
            path: string;
            reason: string;
            /** Format: int32 */
            count: number;
        };
        FindingResponse: {
            kind: string;
            pages: string[];
            text: string;
        };
        PageChangeResponse: {
            /** Format: uuid */
            pageId: string;
            path: string;
            after: components["schemas"]["RevisionResponse"];
            before: components["schemas"]["RevisionResponse"];
            /** Format: int32 */
            lengthBefore: number;
            /** Format: int32 */
            lengthAfter: number;
        };
        RevisionResponse: {
            /** Format: int32 */
            revision: number;
            /** Format: uuid */
            ingestRunId: string;
            path: string;
            title: string;
            description: string;
            type: string;
            markdownBody: string;
            /** Format: date-time */
            createdAt: string;
        };
        RunReportResponse: {
            /** Format: uuid */
            runId: string;
            /** @enum {string} */
            kind: "INGEST" | "REVERT" | "LINT";
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "WRITTEN" | "COMPLETED" | "FAILED";
            /** Format: uuid */
            documentId: string;
            /** Format: int32 */
            attempt: number;
            retryable: boolean;
            failureReason: string;
            /** Format: int32 */
            supersessionCount: number;
            supersessionSkipped: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string;
            pages: components["schemas"]["PageChangeResponse"][];
            supersessions: components["schemas"]["RunSupersessionResponse"][];
            failures: components["schemas"]["FailureResponse"][];
            findings: components["schemas"]["FindingResponse"][];
            revertOffered: boolean;
        };
        RunSupersessionResponse: {
            /** Format: uuid */
            supersessionId: string;
            sectionAnchor: string;
            supersededPath: string;
            supersedingPath: string;
        };
        NextQuestionResponse: {
            /** Format: int32 */
            index: number;
            /** Format: int32 */
            total: number;
            question: string;
        };
        TurnSummaryResponse: {
            question: string;
            answer: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        PageResponse: {
            /** Format: uuid */
            pageId: string;
            path: string;
            title: string;
            description: string;
            type: string;
            /** Format: int32 */
            revision: number;
            markdown: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        IndexEntryResponse: {
            path: string;
            title: string;
            description: string;
            type: string;
        };
        IndexResponse: {
            markdown: string;
            pages: components["schemas"]["IndexEntryResponse"][];
        };
        DanglingSupersessionResponse: {
            /** Format: uuid */
            supersessionId: string;
            supersededPath: string;
            sectionAnchor: string;
            supersedingPath: string;
        };
        DuplicateTitleResponse: {
            title: string;
            paths: string[];
        };
        HealthResponse: {
            danglingLinks: components["schemas"]["LinkFindingResponse"][];
            wrongDirectoryLinks: components["schemas"]["LinkFindingResponse"][];
            orphanConcepts: string[];
            duplicateConceptTitles: components["schemas"]["DuplicateTitleResponse"][];
            danglingSupersessions: components["schemas"]["DanglingSupersessionResponse"][];
            /** Format: int32 */
            indexTokens: number;
            /** Format: int32 */
            indexCeilingTokens: number;
            prefilterDue: boolean;
            latestReview: components["schemas"]["ReviewResponse"];
        };
        LinkFindingResponse: {
            sourcePath: string;
            targetPath: string;
            livePath: string;
        };
        ReviewResponse: {
            /** Format: uuid */
            runId: string;
            /** Format: date-time */
            finishedAt: string;
            findings: components["schemas"]["FindingResponse"][];
        };
        GraphResponse: {
            pages: components["schemas"]["IndexEntryResponse"][];
            links: components["schemas"]["LinkResponse"][];
        };
        LinkResponse: {
            sourcePath: string;
            targetPath: string;
        };
        StreamingResponseBody: unknown;
        DocumentResponse: {
            /** Format: uuid */
            documentId: string;
            /** Format: uuid */
            knowledgeBaseId: string;
            lessonId: string;
            lessonTitle: string;
            sourceFilename: string;
            mimeType: string;
            /** Format: date-time */
            createdAt: string;
            latestRun: components["schemas"]["RunStateResponse"];
        };
        RunStateResponse: {
            /** Format: uuid */
            runId: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "WRITTEN" | "COMPLETED" | "FAILED";
            retryable: boolean;
            failureReason: string;
        };
        ErrorResponse: {
            error?: string;
            code?: string;
            detail?: string;
            lessonId?: string;
            lessonTitle?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KnowledgeBaseResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
        };
    };
    revert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A run is active, or revert is not offered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSessionRequest"];
            };
        };
        responses: {
            /** @description Started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuizSessionResponse"];
                };
            };
            /** @description Nothing to ask about in the scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuizSessionResponse"];
                };
            };
        };
    };
    answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description The quiz is over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EvaluationResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnSummaryResponse"][];
                };
            };
        };
    };
    start_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuerySessionResponse"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                interactionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            /** @description No such conversation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnswerResponse"];
                };
            };
        };
    };
    edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                interactionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Queued; follow the run's report */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
        };
    };
    startLint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description A full review is already queued or running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
        };
    };
    review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FlashcardResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"][];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: {
                lessonId?: string;
                newVersion?: boolean;
            };
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Accepted, or the id of the identical document already here */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentAcceptedResponse"];
                };
            };
            /** @description The lesson exists; send newVersion or another lessonId */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentAcceptedResponse"];
                };
            };
            /** @description Refused upload, invalid lesson id, or a new version of no lesson */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentAcceptedResponse"];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description The latest run is not FAILED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered; the session cookie is set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description The email already has an account */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            /** @description No such knowledge base */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A run is active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunSummaryResponse"][];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No such run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunReportResponse"];
                };
            };
        };
    };
    next: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quiz is over */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NextQuestionResponse"];
                };
            };
        };
    };
    progress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    page: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                directory: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No live page at the path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponse"];
                };
            };
        };
    };
    revisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                directory: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevisionResponse"][];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IndexEntryResponse"][];
                };
            };
        };
    };
    index: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IndexResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    graph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GraphResponse"];
                };
            };
        };
    };
    deck: {
        parameters: {
            query?: {
                lessonId?: string;
                pageId?: string;
            };
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No such lesson or page */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FlashcardResponse"][];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A zip rendered and validated before it is sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": components["schemas"]["StreamingResponseBody"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    removeSupersession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kbId: string;
                supersessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A run is active, or there is no such supersession */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunAcceptedResponse"];
                };
            };
        };
    };
}
